<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="1" skipped="1">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-12-27T11:48:28 IST" name="Default suite" finished-at="2023-12-27T11:48:48 IST" duration-ms="19642">
    <groups>
    </groups>
    <test started-at="2023-12-27T11:48:28 IST" name="Default test" finished-at="2023-12-27T11:48:48 IST" duration-ms="19642">
      <class name="testNGpractice.DependsOnMethodsEx">
        <test-method signature="testpre()[pri:0, instance:testNGpractice.DependsOnMethodsEx@3e11f9e9]" started-at="2023-12-27T11:48:28 IST" name="testpre" finished-at="2023-12-27T11:48:48 IST" duration-ms="19496" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[both Urls not macthed expected [https://www.face] but found [https://www.facebook.com/login.php]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: both Urls not macthed expected [https://www.face] but found [https://www.facebook.com/login.php]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at testNGpractice.DependsOnMethodsEx.testpre(DependsOnMethodsEx.java:23)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testpre -->
        <test-method signature="testpro()[pri:0, instance:testNGpractice.DependsOnMethodsEx@3e11f9e9]" started-at="2023-12-27T11:48:48 IST" name="testpro" finished-at="2023-12-27T11:48:48 IST" depends-on-methods="testNGpractice.DependsOnMethodsEx.testpre" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method testNGpractice.DependsOnMethodsEx.testpro() on instance testNGpractice.DependsOnMethodsEx@3e11f9e9 depends on not successfully finished methods 
[testNGpractice.DependsOnMethodsEx.testpre() on instance testNGpractice.DependsOnMethodsEx@3e11f9e9]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method testNGpractice.DependsOnMethodsEx.testpro() on instance testNGpractice.DependsOnMethodsEx@3e11f9e9 depends on not successfully finished methods 
[testNGpractice.DependsOnMethodsEx.testpre() on instance testNGpractice.DependsOnMethodsEx@3e11f9e9]
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:156)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testpro -->
      </class> <!-- testNGpractice.DependsOnMethodsEx -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
